name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: explore environment
        run: |
          7z
          curl --version
          git --version
          hg --version
          jq --version
          python --version
      #- name: find task
      #  run: |
      #    curl -sL https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task-group/C02r2EkOTBauTVFINs-kOQ/list --output task-group.json
      #    jq --arg workerType 't-win10-64' '[ .tasks[] | select(.status.workerType == $workerType) ]' task-group.json > t-win10-64.json
      #    jq '.[0]' t-win10-64.json > task.json
      #- name: extract mozharness
      #  run: |
      #    jq -r '.task.payload.mounts[] | select(.format == \"zip\" and .directory == \"mozharness\") | .content.taskId' task.json
      - name: extract mozharness
        run: |
          curl -L https://hg.mozilla.org/mozilla-central/raw-file/50c8711162bd0aa7931a425f1bd77e85c1f05ce5/taskcluster/scripts/misc/fetch-content --output fetch-content
          curl -L https://hg.mozilla.org/mozilla-central/raw-file/50c8711162bd0aa7931a425f1bd77e85c1f05ce5/taskcluster/scripts/run-task --output run-task
          curl -L https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/AflwW4nqTm2fTsFlBwZhFQ/artifacts/public/build/mozharness.zip --output mozharness.zip
          7z x -o mozharness mozharness.zip
          dir
      - name: run task
        run: |
          dir mozharness
          python run-task -- python -u mozharness\scripts\desktop_unittest.py --cfg mozharness\configs\unittests\win_unittest.py --mochitest-suite=mochitest-devtools-chrome --code-coverage --setpref=media.peerconnection.mtransport_process=false --setpref=network.process.enabled=false --enable-webrender --setpref=layers.d3d11.enable-blacklist=false --download-symbols ondemand
