name: CI
on:
  push:
    branches:
      - main
jobs:
  win64-plain-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: find task
        run: |
          curl -sL https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.mozilla-central.latest.firefox.win64-plain-opt --output indexed-build-task.json
          curl -sL https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/$(jq -r '.taskId' indexed-build-task.json) --output build-task.json
          jq '.' build-task.json
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: explore environment
        run: |
          curl --version
          git --version
          hg --version
          jq --version
          python --version
      #- name: find task
      #  run: |
      #    curl -sL https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task-group/C02r2EkOTBauTVFINs-kOQ/list --output task-group.json
      #    jq --arg workerType 't-win10-64' '[ .tasks[] | select(.status.workerType == $workerType) ]' task-group.json > t-win10-64.json
      #    jq '.[0]' t-win10-64.json > task.json
      #- name: extract mozharness
      #  run: |
      #    jq -r '.task.payload.mounts[] | select(.format == \"zip\" and .directory == \"mozharness\") | .content.taskId' task.json
      - name: extract mozharness
        run: |
          curl -L https://hg.mozilla.org/try/raw-file/7d38fea9318fd3e687a88a90ddef1f4b08495975/taskcluster/scripts/misc/fetch-content --output fetch-content
          curl -L https://hg.mozilla.org/try/raw-file/7d38fea9318fd3e687a88a90ddef1f4b08495975/taskcluster/scripts/run-task --output run-task
          curl -L https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/EZsDbe9aQGyZkw4K3F8FJw/artifacts/public/build/mozharness.zip --output mozharness.zip
          7z x -omozharness mozharness.zip
      - name: install deps
        run: |
          python -m pip cache dir
          python -m pip install --upgrade zstandard
          python -m pip install --upgrade certifi
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pypiwin32
          python -m pip install --upgrade wheel
          python -m pip install --upgrade virtualenv
          md c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\virtualenv_support
          curl -L https://files.pythonhosted.org/packages/f2/16/3eb9c66a7bfb5220c7bcbaaac33d359fe8a157b028959cd210983749b2e0/Twisted-21.2.0-py3-none-any.whl --output c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\virtualenv_support\Twisted-21.2.0-py3-none-any.whl
          python -m pip install --upgrade c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\virtualenv_support\Twisted-21.2.0-py3-none-any.whl
      - name: run task
        env:
          TASKCLUSTER_ROOT_URL: https://firefox-ci-tc.services.mozilla.com
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
          MOZ_FETCHES: "[{\"artifact\": \"public/build/fix-stacks.tar.bz2\", \"extract\": true, \"task\": \"Lhs91AvoT-28yyuTcna2Gw\"}, {\"artifact\": \"public/build/minidump_stackwalk.tar.xz\", \"extract\": true, \"task\": \"R1KCnxRaToGjTtbWHHBZgA\"}]"
          MOZ_SCM_LEVEL: 1
          GECKO_HEAD_REV: 7d38fea9318fd3e687a88a90ddef1f4b08495975
          MOZ_AUTOMATION: 1
          MOZ_FETCHES_DIR: fetches
          SCCACHE_DISABLE: 1
          GECKO_HEAD_REPOSITORY: https://hg.mozilla.org/try
          MOZHARNESS_TEST_PATHS: "{\"mochitest-devtools-chrome\": [\"devtools/client/aboutdebugging/test/browser/browser.ini\", \"devtools/client/application/test/browser/browser.ini\", \"devtools/client/framework/test/browser-enable-popup-devtools-user.ini\", \"devtools/client/framework/test/browser-enable-popup-new-user.ini\", \"devtools/client/inspector/compatibility/test/browser/browser.ini\", \"devtools/client/inspector/test/browser.ini\", \"devtools/client/performance/test/browser.ini\", \"devtools/client/shared/sourceeditor/test/browser.ini\", \"devtools/server/tests/browser/browser.ini\", \"devtools/shared/commands/inspector/tests/browser.ini\", \"devtools/shared/webconsole/test/browser/browser.ini\", \"devtools/startup/tests/browser/browser.ini\"]}"
          EXTRA_MOZHARNESS_CONFIG: "{\"installer_url\": \"https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/EZsDbe9aQGyZkw4K3F8FJw/artifacts/public/build/target.zip\", \"test_packages_url\": \"https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/EZsDbe9aQGyZkw4K3F8FJw/artifacts/public/build/target.test_packages.json\"}"
        run: |
          python run-task -- python -u mozharness\scripts\desktop_unittest.py --cfg mozharness\configs\unittests\win_unittest.py --mochitest-suite=mochitest-devtools-chrome --setpref=media.peerconnection.mtransport_process=false --setpref=network.process.enabled=false --download-symbols ondemand
