name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: explore environment
        run: |
          curl --version
          git --version
          hg --version
          jq --version
          python --version
