name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: explore environment
        run: |
          curl --version
          git --version
          hg --version
          jq --version
          python --version
      - name: find tasks
        run: |
          curl -sL https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task-group/C02r2EkOTBauTVFINs-kOQ/list --output task-group.json
          jq '.' task-group.json
